export const PLATFORM_TOKEN_SUCCESS = 'PLATFORM_TOKEN_SUCCESS'
export const LOGIN_TOKEN_SUCCESS = 'LOGIN_TOKEN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const UPDATE_TWO_FA_STATUS = 'UPDATE_TWO_FA_STATUS'
export const UPDATE_TYPE = 'UPDATE_TYPE'
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'

