const words_he = {
  login: 'כניסה',
  login_success: 'התחברת בהצלחה',
  logout_success: 'התנתקת בהצלחה',
  email_success: 'אימייל נשלח בהצלחה',
  reset_password_success: 'סיסמא אופסה בהצלחה',
  schedule_event_created: 'לוח אירועים נוצר בהצלחה',
  cost_created: 'עלויות נוצר בהצלחה',
  client_created: 'לקוח נוצר בהצלחה',
  client_updated: 'לקוח עודכן בהצלחה',
  client_deleted: 'לקוח נמחק',
  user_created: 'משתמש נוצר בהצלחה',
  user_updated: 'משתמש עודכן בהצלחה',
  user_deleted: 'משתמש נמחק',
  supplier_created: 'ספק נוצר בהצלחה',
  supplier_updated: 'ספק עודכן בהצלחה',
  supplier_deleted: 'ספק נמחק',
  event_created: 'אירוע נוצר בהצלחה',
  event_updated: 'אירוע עודכן בהצלחה',
  file_created: 'הקובץ נוצר בהצלחה',
  hello: 'שלום',
  please_sign_in: 'אנא התחבר/י',
  home: 'בית',
  register: 'הרשמה',
  create_new_user: 'יצירת משתמש',
  logout: 'התנתקות',
  name: 'שם',
  email: 'כתובת מייל',
  username: 'שם משתמש',
  password: 'סיסמה',
  new_password: 'סיסמה חדשה',
  confirm_password: 'סיסמה בשנית',
  forgot_password: 'שכחתי סיסמה',
  send: 'שלח',
  reset_password: 'איפוס סיסמה',
  users: 'משתמשים',
  user: 'משתמש',
  update_user: 'ערוך משתמש',
  admin: 'מנהל',
  active: 'פעיל',
  not_active: 'לא פעיל',
  edit: 'ערוך',
  delete: 'מחק',
  status: 'סטטוס',
  update_at: 'עודכן בתאריך',
  phone: 'מספר פלאפון',
  new_bid: 'הצעת מחיר חדשה',
  bid_id: 'מספר הצעת מחיר',
  permissions: 'הרשאות',
  first_name: 'שם פרטי',
  last_name: 'שם משפחה',
  languages: 'שפות',
  language: 'שפה',
  hebrew: 'עברית',
  event_type: 'סוג אירוע',
  client_name: 'שם הלקוח',
  location: 'מיקום',
  event_name: 'שם האירוע',
  comments: 'הערות',
  participants_amount: 'כמות משתתפים',
  minimum: 'מינימום',
  maximum: 'מקסימום',
  time_schedule_for_event: 'לוח זמנים לאירוע',
  start_time: 'משעה',
  end_time: 'עד שעה',
  activity_description: 'תיאור הפעילות',
  costs: 'עלויות',
  description: 'תיאור',
  amount: 'כמות',
  unit_cost: 'מחיר ליחידה',
  total_cost: 'מחיר כולל',
  discount: 'הנחה',
  comment: 'הערה',
  currency: 'מטבע',
  bit_status: 'סטטוס הצעה',
  total_cost_before_discount: 'סה"כ לפי הנחה',
  total_discount: 'סה"כ הנחה',
  total_cost_after_discount: 'סה"כ אחרי הנחה',
  save: 'שמור',
  clear_all: 'נקה הכול',
  cancel_and_exit: 'ביטול ויציאה',
  nis: 'שקל',
  dollar: 'דולר',
  draft: 'טיוטה',
  sent: 'נשלח',
  approved: 'אושר',
  bid_status: 'סטטוס הצעה',
  search: 'חיפוש...',
  sum_rows: 'סך התוצאות: ',
  rows_to_display: 'שורות להצגה',
  server_error: 'שגיאת שרת',
  error_accord: 'אירעה שגיאה אנא בדוק את הנתונים ונסה שנית',
  login_error: 'שם משתמש או סיסמא לא נכונים',
  failed_load_data: 'נכשל לטעון מידע',
  type_in_en: 'הקלד באנגלית',
  type_number: 'הקלד מספר',
  yes: 'כן',
  no: 'לא',
  cancel_exit: 'אתה בטוח שאתה רוצה לצאת?',
  bids: 'הצעות מחיר',
  profile_settings: 'הגדרות פרופיל',
  password_not_matched: 'הסיסמאות אינן תואמות',
  user_name: 'שם משתמש',
  permission_level: 'רמת הרשאה',
  change_password: 'שינוי סיסמה',
  old_password: 'סיסמה נוכחית',
  locatin_name: 'שם מיקום',
  clients: 'לקוחות',
  client: 'לקוח',
  private: 'פרטי',
  type: 'סוג',
  department: 'מחלקה',
  company: 'חברה',
  guest: 'אורח',
  event_date: 'תאריך האירוע',
  new_client: 'לקוח חדש',
  update_client: 'ערוך לקוח',
  new_event: 'אירוע חדש',
  add_client: 'הוספת לקוח',
  from_date: 'מתאריך',
  to_date: 'עד תאריך',
  end_after_start: 'שעת הסיום צריכה להיות אחרי שעת ההתחלה',
  end_date_after_start: 'תאריך הסיום צריך להיות אחרי תאריך ההתחלה',
  create_event: 'צור אירוע חדש',
  events: 'אירועים',
  public: 'ציבורי',
  inside: 'בפנים',
  photo_shot: 'צילומים',
  pending: 'ממתין לאישור',
  canceled: 'בוטל',
  suppliers: 'ספקים',
  account_details: 'פרטי חשבון',
  account_name: 'שם בעל החשבון',
  add_supplier: 'הוספת ספק',
  new_supplier: 'ספק חדש',
  reports: 'יצירת דוחות',
  display_event: 'האירוע שנבחר',
  edit_event: 'ערוך אירוע',
  pick_client: 'בחר לקוח או הוסף חדש ',
  download_file_title: 'הקובץ מוכן להורדה',
  download_file: 'לחץ להורדה',
  create_csv: 'צור קובץ csv',
  employee_name: 'יוצר האירוע',
  download_pdf: 'הורד PDF',
  send_to_email: 'שלח למייל',
  create_pdf: 'צור קובץ PDF',
  finish: 'סיום',
  next: 'הבא',
  back: 'חזור',
  skip: 'דלג',
  tables: 'טבלאות',
  time_schedule: 'לוח זמנים',
  bid_created: 'הצעת מחיר נוצרה בהצלחה',
  created_at: 'תאריך יצירה',
  english: 'אנגלית',
  updated_at: 'עודכן בתאריך',
  invalid_character: 'הכנסת תו לא חוקי',
  download_pdf_title: 'קובץ PDF  להורדה או לשליחה למייל',
  update_supplier: 'ערוך ספק',
  welcome: 'מערכת ניהול אירועים',
  reports_content_row1: 'קובץ CSV הוא סוג מיוחד של קובץ שניתן ליצור או לערוך בפלטפורמת Excel.',
  reports_content_row2: 'שלבי ייצוא קובץ CSV של המידע המאוחסן בטבלאות מסד הנתונים של המערכת במהירות ופשטות:',
  reports_content_row3: '1. בחרו את הטבלה המכילה את הנתונים הרצויים לייצוא.',
  reports_content_row4: '2. בחרו את טווח התאריכים בו מעוניינים (אופציונלי).',
  reports_content_row5: '3. לחצו על כפתור "צור קובץ CSV".',
  allDay: 'כל היום',
  previous: 'הקודם',
  today: 'היום',
  month: 'חודש',
  week: 'שבוע',
  day: 'יום',
  agenda: 'בתוכנית',
  date: 'תאריך',
  time: 'זמן',
  event: 'אירוע',
}

module.exports = {
  words_he,
}
