const words_he = {
  welcome: 'ברוכים הבאים למוזיאון ישראל',
  login: 'כניסה',
  hello: 'שלום',
  please_sign_in: 'אנא התחבר/י',
  home: 'בית',
  register: 'הרשמה',
  logout: 'התנתקות',
  name: 'שם',
  email: 'כתובת מייל',
  username: 'שם משתמש',
  password: 'סיסמה',
  new_password: 'סיסמה חדשה',
  confirm_password: 'סיסמה בשנית',
  forgot_password: 'שכחתי סיסמה',
  send: 'שלח',
  reset_password: 'איפוס סיסמה',
  users: 'משתמשים',
  user: 'משתמש',
  admin: 'מנהל',
  active: 'פעיל',
  not_active: 'לא פעיל',
  edit: 'ערוך',
  delete: 'מחק',
  status: 'סטטוס',
  permissions: 'הרשאות',
  update_at: 'עודכן בתאריך',
}

module.exports = {
  words_he,
}
